### ISSUE TITLE
How to use IMAP function 📧

### ISSUE THREAD

**Issue by krillin666** [seanbreckenridge/HPI#15]
Hello,

Thanks for this amazing extension of HPI that I just discovered. I was trying to setup this with Promnesia for my emails but I'm getting zero indexing:

```
[INFO    2021-10-18 23:17:26 promnesia extract.py:49] extracting via promnesia_sean.sources.imap:index () {} ... ...
[INFO    2021-10-18 23:17:26 promnesia extract.py:82] extracting via promnesia_sean.sources.imap:index () {} ...: got 0 visits
```
I am using this [Thunderbird Addon](https://addons.thunderbird.net/en-US/thunderbird/addon/importexporttools-ng/) and I've tried to export with using:
-    Export whole folder
-    Export whole folder with structure
-    Export all emails in EML format
-    Export all email in TXT format

All these export are in my .local/share/mail path, I even wrote the path literally in the __init___ file instead of using `path,join` but nothing works.

Thank you so much !

**Comment by seanbreckenridge** [comment]
Ah - may also be some issue with the different date format that the thunderbird addonn uses, looking into that

**Comment by krillin666** [comment]
Wow that was fast 😅. First of all, let me thank you for fixing this and showing the appropriate steps.

I've now been able to index on of my Inboxs to test the display in Promnesia.
However, it was not what I was expecting and maybe you can improve them (I can try too but I'm not a coder).

Before using your IMAP source I was using the *plaintext* source from Promnesia and it was at least displaying surrounding text of the email body next to the URL. With your source I just get the file name.

 Nevertheless, yours has the advantage of having the email date! What I was trying to accomplish before (and thought that yours implemented) was to display the surrounding text but also the Date, From, Subject, To fields in the promnesia plugin. 

I've two more comments:

1. When I installed your Promnesia package the sources folder is not installed and I had `svn checkout https://github.com/seanbreckenridge/promnesia/trunk/promnesia_sean/sources` inside the promnesia_sean folder.
2. I've came up with this question pertaining to security and maybe I should direct it to karli but I think you are in the position to answer it too: Using sources that index sensitive information (like email) is it possible to add a prompt option on the `promnesia index` for a password to encrypted folders which are given to some sources (like the IMAP, or the plaintex/auto) ? We could put it in the config.py file but that defeats the purpose because in that case would be scrapable to an attacker

Thank you so much again for your help and work !

**Comment by seanbreckenridge** [comment]
> displaying surrounding text of the email body next to the URL

Theres an option in my promnesia module to display the text as the body, but with 8000 emails, the sqlite database tends to grow pretty fast (was something like 30GB on my end, since it copies the text for every URL it finds)

See https://github.com/seanbreckenridge/promnesia/blob/master/promnesia_sean/sources/imap.py#L30

To enable that, in your config you can do something like:

`Source(imap, body_as_context=True)` instead of just the `imap` like in [my config](https://sean.fish/d/config.py?dark)

> svn checkout

Hmm, am not sure if this is related to it being a namespace package, but I sorta doubt it. Don't have any experience with svn

> question pertaining to security

Yeah, I've thought about this a bit as well. The best solution that perhaps I've come across for something like this is to use something like [`pass`](https://www.passwordstore.org/), which PGP encrypts your password, and then use that to store a decryption key for some local zip? It adds a bunch of complexity, but [core.structure](https://github.com/karlicoss/HPI/pull/175) already exists, which abstracts away some of the unzipping/extraction.

Since everything is local-first, I sort of don't see a huge issue, but if you want to bring it up, best place would probably be [here](https://github.com/karlicoss/promnesia/issues/14)

**Comment by krillin666** [comment]
Since all emails in plaintext begin like so:
```
   1   │ Subject: Promnesia
   2   │ From: John Doe
   3   │ Date: 06/10/2021, 09:28
   4   │ To: Someone
```
It would suffice to use something simple like this for each email file:

```python
From = ""
To = ""
Subject = ""
Date = ""
with open(email_file) as in_file:
    
    for line in in_file:
        
        if "From" in line.strip():
            From = line.strip()
            # etc etc

        #If we want to obtain only the text after the From, To:
        From.split(":",1)[0]
        # etc etc
        # Maybe we can just keep it ?
```
I'm sure you'll know the best way though !

**Comment by seanbreckenridge** [comment]
> relation to extracting and displaying the From, To, Subject

I think its already doing this?

![2021-10-19--10_44_33](https://user-images.githubusercontent.com/7804791/137963891-1b1e2022-6fd2-4905-93f5-e69a82d5b153.png)
 
Relevant code is [here](https://github.com/seanbreckenridge/promnesia/blob/master/promnesia_sean/sources/imap.py#L46)

I'll take a look at the markdown/plaintext modules from promnesia to see how they do it and see if I can figure out surrounding text; will leave this issue open for that purpose

**Comment by seanbreckenridge** [comment]
> It would suffice (???) to use something simple like this for each email file :

As just an FYI, [`mail-parser`](https://pypi.org/project/mail-parser/) (library which wraps the stdlib [`email`](https://docs.python.org/3/library/email.html) lib is what `my.imap` uses, and that already parses all that info out of it nicely, so no need to try to do it manually:

https://github.com/seanbreckenridge/HPI/blob/master/my/imap.py#L72-L95

**Comment by krillin666** [comment]
> > relation to extracting and displaying the From, To, Subject
> 
> I think its already doing this?
> 
> ![2021-10-19--10_44_33](https://user-images.githubusercontent.com/7804791/137963891-1b1e2022-6fd2-4905-93f5-e69a82d5b153.png)
> 
> Relevant code is [here](https://github.com/seanbreckenridge/promnesia/blob/master/promnesia_sean/sources/imap.py#L46) 👁canonical: [github.com/seanbreckenridge/promnesia/blob/master/promnesia_sean/sources/imap.py](https://github.com/seanbreckenridge/promnesia/blob/master/promnesia_sean/sources/imap.py)×?sources : firefox18/10/2021, 21:21:36
> 
> It displays that as the Locator description, not the body -- don't think that should make a difference though, I think thats always shown
> 
> I'll take a look at the markdown/plaintext modules from promnesia to see how they do it and see if I can figure out surrounding text; will leave this issue open for that purpose

Ok I see. But what I was trying to achieve was to have something like:
```

From: Sean
To: Krillin
Subject: IMAP issue

"Relevant text around url from email body here"
```
I see that the date is nicely displayed already on the Promnesia addon in the same location as for browser history, so no need to extract that line 👍 

Thank you again and looking out how this goes 😀

**Comment by seanbreckenridge** [comment]
Since I think the config issues around IMAP has generally been solved here, gonna move it to an issue [on the promnesia repo](https://github.com/seanbreckenridge/promnesia/issues/1)

**Comment by krillin666** [comment]
> I tested out [the addonn](https://addons.thunderbird.net/en-US/thunderbird/addon/importexporttools-ng/), and I think I've got it to work. Using the 'Plain Text Format', export that to a folder somewhere.
> 
> It takes a while to do so:
> 
> ![image](https://user-images.githubusercontent.com/7804791/137866723-588e39a0-5cca-4feb-9647-37f526375eee.png)
> 
> I just put that in `~/Downloads/mailexport` for this demo.

> This does mean you'd have to periodically do an export, but there isn't a great way around that with thunderbird. For context, I use [mutt-wizard](https://github.com/LukeSmithxyz/mutt-wizard), which uses [mbsync](https://isync.sourceforge.io/mbsync.html) under the hood, so my mail gets synced with a local folder once every 5 minutes.

Sorry for commenting on a closed issue. I've found a way to automate this process for Thunderbird users, however it relies on using MBOX type files.
The addon mentioned for Thunderbird (importexporttols) now supports periodic Backups but only in MBOX format. 
I've seen this solution to parse MBOX files: https://github.com/chronicle-app/chronicle-email/blob/master/lib/chronicle/email/mbox_extractor.rb

Maybe this could be ported to promnesia, don't know how laborious that would be. 
Thank you !
